#!/bin/bash

#Copy liste.txt from users/linfg/linfg0/S3/ repository to the main repository.
cp liste.txt ../../../

#Display the content of liste.txt file.
cd ../../../
more liste.txt

#Control the permission about this file.
chmod 766 liste.txt

#Revoke the writing permission.
chmod 444 liste.txt

#Change once name in this file by using an editor text then save & quit.
gedit liste.txt
#We can not write into liste.txt

#Grant the writing permission.
chmod 644 liste.txt

#Change once name in this file by using an editor text then save & quit.
gedit liste.txt
